server:
  address:
  port: 8088

spring:
  datasource:
    url: jdbc:h2:~/FIAP/Fase03/livraria/h2database-fiap;DB_CLOSE_ON_EXIT=FALSE
    username: fiap
    passsword: fiap
    hikari:
      auto-commit: true