server:
  address:
  port: 8088

spring:
  datasource:
    url: jdbc:h2:D:/FIAP/Fase 03/datasource/livraria/h2database-fiap;AUTO_SERVER=TRUE
    username: fiap
    password: fiap
    hikari:
      auto-commit: true

jwt:
  secret: f1apPs3cr47
  expire: 5